name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run PSScriptAnalyzer
      shell: powershell
      run: |
        Invoke-ScriptAnalyzer -Path .\src -Recurse -Severity Error

    - name: Run Pester Tests
      shell: powershell
      run: |
        Invoke-Pester -Path .\tests -PassThru

    - name: Create Release Zip
      shell: powershell
      run: |
        Compress-Archive -Path .\src, .\IlumnulOS.ps1, .\README.md -DestinationPath IlumnulOS.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: IlumnulOS
        path: IlumnulOS.zip

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: IlumnulOS
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: IlumnulOS.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
